backend/package.json
frontend/package.json

Initialize folders for frontend and backend

Set up initial folder structure

---

.eslintignore
.eslintrc
.travis.yml
backend/package-lock.json
frontend/.prettierrc
frontend/package-lock.json
frontend/package.json
package-lock.json
package.json

Added config for automated style checking

eslint and Travis

---

package.json

--fix flag prevents eslint from failing on fixable problems. It's useful when you run on your own machine but produces false positives when run as part of CI

Fix eslint command

---

frontend/src/components/RegisterForm.js
frontend/src/pages/RegisterPage.js

Similar to login page, this is very barebones form that we can modify and build out auth logic at a later stage once we have other parts in motion. Minimal styling, also I have not built out a robust validation, relying on native HTML validation we would need to work on server side validation in the future.
#11

adding register page

---

backend/Makefile

Forgot to add `clean` in the previous pr. Sorry about that

Add `clean` to the directives list

---

backend/docker/dev/docker-compose.yml

Another addition to the config, the app will be listening on port 8000 of the laptop/vm with docker.

expose port 8000 in a docker config, to make the app accessible

---

.gitignore
backend/.gitignore
backend/src/app.js
backend/src/package-lock.json
backend/src/package.json
frontend/.eslintrc
frontend/components/GoogleRegisterButton.js
frontend/components/LoginForm.js
frontend/components/Navbar.js
frontend/components/Profile.js
frontend/components/RegisterForm.js
frontend/components/UserProvider.js
frontend/package-lock.json
frontend/package.json
frontend/pages/login.js
frontend/pages/profile.js
frontend/pages/register.js
frontend/styles/StyledErrorMsg.js

Connected Register and Log in buttons with the back end.
Added profile page: it's almost empty right now but I thought it's still worth it to include it in the PR as an example of how to read data from the React context. 
Also, error messages are currently not descriptive enough -- I think we need to change some backend routes to fix it (right now there is no way of knowing on the front end what went wrong).

Register and Log in buttons

---

.eslintignore
.gitignore
backend/src/.eslintingore
backend/src/migrations/1543523539612_init.js
backend/src/models/EventAttendee.js
backend/src/models/User.js
backend/src/package-lock.json
backend/src/package.json
backend/src/routes/users.js
backend/src/utils/upload.js

1. Added `image` field to user model. Contains URL of user image/avatar.
2. Added endpoint to upload images - `POST users\images`
It will store file in the folder set with `UPLOADS_FOLDER` envvar and return `url` of newly uploaded image.
Env variables `SITE_URL` and `STATIC_PATH` define URL where static files are served(with Nginx for example).
Images must be uploaded as multipart/form-data with `name` attribute set to `file`. Make sure to set `content-type` header to `multipart/form-data`
There's just dumb mime-type check to accept images only. All files should be under 500K in size.
I generate filenames based on user id, so if user uploads new image - it will overwrite previous one(unless new file has different extension) and save us some space.

User images/avatars

---

.travis.yml
backend/src/migrations/1543523539612_init.js
backend/src/models/Activity.js
backend/src/models/Event.js
backend/src/models/EventAttendee.js
backend/src/models/Place.js
backend/src/models/Table.js
backend/src/models/User.js
backend/src/routes/events.js

1. Added `image` field to the events table and all corresponding endpoints.
2. Added endpoint `GET events/:id/attendees` which returns all attendees of the event.
3. Added check for required fields in all create operations.
4. Added check to `POST events/:id/attend` to prevent oversubscribing.

Add image field to events table

---

frontend/components/EventList.js
frontend/pages/events.js

May need to refactor this later. But it works for now. Button fetches the next 5 events in the database repeatedly, until there is nothing to fetch.

load more button and pagination

---

backend/Makefile
backend/integration_tests/test/test_app.js
backend/readme.MD
backend/src/models/Table.js

1. Updated API specs
2. Fixed bug in `Makefile` when failed tests did not broke build run.

Specs update

---

frontend/pages/login.js
frontend/pages/register.js

If user is in Login page we have a link to register page (in case user needs new account) and in reverse - if user is in Register page we can link to login page.

linking register and login pages together

---

backend/src/app.js
backend/src/middleware/googleStrategy.js

Added delegation to internal express error handler.

Bug fix in the error handler

---

Makefile
deploy/resources.tf
deploy/variables.tf
docker/release/Dockerfile-frontend

Added envvars for Cloudinary credential and updated frontend dockerfile.

Deploy configs

---

deploy/resources.tf

Exposed two environmental variables with FQDN and port of the backend, `API_HOST` and `API_PORT`.

pass fqdn and port to frontend as envvar

---

frontend/.eslintrc
frontend/components/EventListItem.js
frontend/components/Footer.js
frontend/components/LoginButton.js
frontend/components/MainLayout.js
frontend/components/Navbar.js
frontend/components/NewEventForm.js
frontend/components/Profile.js
frontend/pages/_document.js
frontend/pages/event.js
frontend/pages/events.js
frontend/pages/newevent.js

Make footer stick to the bottom of the page or content, whichever is taller.

Fix footer

---

frontend/components/GoogleRegisterButton.js
frontend/components/LoginForm.js
frontend/components/UserProvider.js

Connected Google Auth button with back end. @trolleksii have a look if you have time please.

Connect Google Auth workflow to back end

---

.eslintrc
backend/src/package.json
backend/src/routes/users.js
backend/src/utils/upload.js
frontend/components/ImageUploader.js
frontend/components/LoginForm.js
frontend/components/Profile.js
frontend/components/UserProvider.js
frontend/package.json
frontend/pages/events.js

Implemented user image upload on front end and connected to back end. Thanks @trolleksii for helping out!

User images

---

backend/src/middleware/passport.js
backend/src/models/db.js

Now it's correct, on DB connection error response status code is 500, body is:
```JSON
{
"message": "DB connection error"
}
```

fix bug error status code wasn't passed through login middlware

---

backend/src/routes/events.js
backend/src/routes/users.js

Increased image size limits to 500x500 px.

increased image size limit

---

frontend/.eslintrc
frontend/components/BioModal.js
frontend/components/EditModal.js
frontend/components/GoogleRegisterButton.js
frontend/components/NameModal.js
frontend/components/Profile.js
frontend/components/UserProvider.js
frontend/package-lock.json
frontend/package.json

Added buttons to edit user's first, last names, and bio

Edit first name, last name, bio

---

backend/src/app.js
backend/src/routes/activities.js
backend/src/routes/events.js
backend/src/routes/places.js

Removed requirement to be authenticated to get events/activities/places lists or single items.

remove auth requiremets for get requests

---

backend/src/models/User.js
backend/src/utils/populate_db.js
backend/src/utils/test_db.json

Script to make DB population for tests/showcases easier.
1. cd into `backend/src/utils`
2. Put your data into some file(look at `test_db.json` to get an idea about file structure). All foreign keys use position in array where relevant data is stored as `id`, for example `"author_id": 0` will get id of the the first element of `users` array.
3. Run the script:
```SH
node populate_db.js test_db.json
```

Populate db script

---

backend/src/models/User.js
backend/src/routes/activities.js
backend/src/routes/events.js
backend/src/routes/places.js
backend/src/routes/users.js
backend/src/test/test_models.js

Add entity name to 404 responses(and id where it was possible):
````
{
"message": "place #1442 not found"
}
```

add description to error messages

---

.travis.yml
backend/src/app.js
backend/src/utils/upload.js
deploy/step2/3_host.tf
deploy/step2/variables.tf

1. Restored pieces of code that I accidentally overwrote, related to access permissions for get requests
2. Removed automatic deploy stage of ci/cd pipeline. Now it generates command which may be run by @lkaratun in order to deploy specific branch/version of app. You should see a string in the bottom of the travis build log, something like:
`To plan manual deploy run: terraform plan -var-file=main.tfvars -var image_tag=eb3259d -out tfplan`

Fix authorization issues

---

frontend/components/DynamicLocationSearch.js

Temporary solution to support searching cities in lowercase. Will need to be replaced with proper case-insensitive search later.

[lowercase-search] Support lowercase city search

---

frontend/components/Event.js
frontend/components/ImageUploader.js
frontend/components/Profile.js

Fix error where profile image was changed when event image was uploaded

Fix event and profile image updates

---

backend/src/routes/events.js

Fixed bug that allowed users modify/delete events created by others

restrict mutations to author only

---

README.md

Adding deploy link to readme
